### ISSUE TITLE
Timezone different

### ISSUE THREAD

**Issue by TheCBiker** [jokob-sk/NetAlertX#599]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

I don't know if this is relevant but the time zone in the container is UTC while the zone on the system is CET. That means 1 hour difference. That could cause problems, right? This was correct in the previous version.

### Expected Behavior

Equal Timezones

### Steps To Reproduce

compare date in container console with date in system. 

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
This should be available in the next release. If you can, please have a look at the `pi.alert_dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/Pi.Alert/actions)) from now. 

It would be great if you could test this on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by TheCBiker** [comment]
In the dev image the time zone is correct. Thank you

**Comment by jokob-sk** [comment]
released 🚀 -> closing
