### ISSUE TITLE
Add support for DNSMASQ DHCP lease files

### ISSUE THREAD

**Issue by derekoharrow** [jokob-sk/NetAlertX#661]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Tried using the dhcp plugin against the dnsmasq.leases file and it doesn't work.

### Describe the solution you'd like

DNSmasq uses a different lease file format than DHCPd so I don't believe NetAlertX can interpret it.

Can you please add support for DNSmasq format?

The file is in the following format:

`[Lease expiry time] [mac address] [ip address] [hostname] [client id, if known]`

e.g.

`1715932537 5c:87:9c:cf:97:02 192.168.1.115 ryans-laptop 01:5c:87:9c:cf:97:02`

### Describe alternatives you've considered

n/a

### Anything else?

n/a

**Comment by jokob-sk** [comment]
This should be available in the next release. If you can, please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

map your dnsmasq dhcp.leases file into a path that contains the string `dnsmasq`

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by derekoharrow** [comment]
Wow! What took you so long? ;)

I'll give it a go now and report back. Thank you!!

**Comment by derekoharrow** [comment]
Seems to be working great! Thank you!!

**Comment by jokob-sk** [comment]
released -> closing for now

**Comment by mikesalz** [comment]
@jokob-sk I can create a new issue if you wish.  But similar to this closed issue, OPNsense provides an endpoint [`/api/dnsmasq/leases/search`] to list Dnsmasq leases.  I believe you need SSH enabled in order to access the dhcp file listed in this issue.  But for those who wish to keep SSH disabled, the endpoint might be a great alternative.  Sample below.  Thoughts?


```
import json
import requests


OPNSENSE_URL = "https://192.168.1.1:8443"
API_KEY = "REDACTED"
API_SECRET = "REDACTED"

endpoint = f"{OPNSENSE_URL}/api/dnsmasq/leases/search"

response = requests.get(
    endpoint, 
    auth=(API_KEY, API_SECRET), 
    verify=False
)

if response.status_code == 200:
    data = response.json()

    devices = data.get("rows", [])
    
    print(f"Found {len(devices)} active Dnsmasq entries:\n")
    for device in devices:
        hostname = device.get("hostname", "Unknown")
        ip = device.get("address", "N/A")
        mac = device.get("client_id", "N/A")
        mac_info = device.get("mac_info", "N/A"),
        if_descr = device.get("if_descr", "N/A")

        print(f"Host: {hostname} | IP: {ip} | MAC: {mac} | MAC Info: {mac_info} | Interface: {if_descr}")
else:
    print(f"Failed to access Dnsmasq API. Status Code: {response.status_code}")
```

**Comment by jokob-sk** [comment]
Hi @mikesalz ,

Thanks for the suggestion. Yes please open a separate issue. I am leaning toward a new plugin (maybe `DNSMSQAPI` or `OPNSNSAPI`) as the DNSLSS plugin operates by mapping dns leases files into the container and adding a conditional flow seems a bit off - anyhow - happy to hear other suggestions. 

I will also need help implementing this as I don't run OPNSense. If you could create a PR that would be ideal. You can probably check front/plugins/kea_api for inspiration.

**Comment by mikesalz** [comment]
New feature request issue: [Add support for OPNsense Dnsmasq endpoint
](https://github.com/netalertx/NetAlertX/issues/1674)
