### ISSUE TITLE
Just some feedback of the last few releases

### ISSUE THREAD

**Issue by sbe-arg** [jokob-sk/NetAlertX#669]
Nice intentional improvements but the solution is working slower and slower even on fresh installs.
That loading of 30 plugins drives me a bit nuts and the occasional error that partial settings have been saved or loaded.

Its becoming more and more unusable for me in prod to secure my networks if I try to keep up with the breaking changes.

Thanks for the efforts and time but I hope we work on usability and stability more than features.

**Comment by jokob-sk** [comment]
Thanks for the feedback @sbe-arg !
The next big piece I want to spend time on is addressing part of your request,that is I'm thanking to build a plugin loader module allowing users to unload unnecessary modules. This will give shorter startup times a quicker configuration iterations.

Let me know what else would improve the experience and ideally if you can help out 🙏

**Comment by sbe-arg** [comment]
In an ideal world Id like to setup everything from environment variables instead of the GUI so the only things I really need to care is to backup my devices file and re import it if I need to start fresh.

**Comment by sbe-arg** [comment]
I mean yes but not necessarily. If we can re populate everything in the settings via env vars and restore a devices known list you only loose the history of events.

Means we never habe to login to the web ui if we onlt care about notifications of new devices.

Or to accept new devices so they are known.

In my personal use i only care if new devices join a few vlan wifi networks as alert strategy i dont really care about the history more than a few hours.

**Comment by jokob-sk** [comment]
> Means we never habe to login to the web ui if we onlt care about notifications of new devices.

You theoretically don't have to log into the UI even now. The `app.conf` file can be edited manually and restored with the container. Also, currently, you need to log into the UI to restore the `devices.csv` file. 

So far, after re-reading your comments, the priorities for your specific use cases, are:

1. Faster load times
2. Preventing incorrect settings to be saved
3. Settings initialized via env variables

**Number 1)** I addressed in the above comment as something I'm thinking about already (for about 2-3 months at this point)

**Number 2)** from the above should be addressed to some degree in the latest production build. I'm explicitly checking if the core setting UI_LANG is being passed to prevent empty settings to be saved:

https://github.com/jokob-sk/NetAlertX/blob/36af285c0a8065bcf1bbf540ccfe5f495cfd4ec2/front/settings.php#L747

I'm happy to improve on it further, if you have suggestions how to address this issue. 

**Number 3)** I'm more then happy if you or someone helps me to achieve a universal way how to initialize any setting via an ENV variable. This has to be done dynamically as new settings are introduced constantly and maintaining the code otherwise would become unsustainable. This also means when users save the given settings in the UI it may be overridden again - so corresponding UI warnings should ideally be shown.

Regarding 1 & 3 - These are again feature requests, which in essence might introduce new bugs, exactly something you asked me not to do and to focus on the stability of the application. 

I do really understand, and want to make the application more stable myself, but as you can see even this thread introduced at least 2 more significant features to the app 🙂and I'm meaning this in a good way, because I really think those are great ideas, but my personal time (and sanity) doesn't allow for more thorough QA testing and development speed without the help of the community. 

I know you helped me in the past (I think it was making the image smaller?) -  I really appreciate it - so if you decide to help out again, I'm really looking forward to it. 🙏

**Comment by jokob-sk** [comment]
Hi @sbe-arg ,

Regarding 1) Faster load times - I've implemented version v0.5 of this in the `netalertx-dev` image

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/f6033053-0b39-484e-89b8-6224c99d150e)

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by jokob-sk** [comment]
closing -> releasing in ~10min
