### ISSUE TITLE
include attributes to device_tracker

### ISSUE THREAD

**Issue by fama-lama** [jokob-sk/NetAlertX#703]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [X] Yes
- [ ] No

### Is your feature request related to a problem? Please describe

I have an automation in home assistant to notify if any changes to my network, such as if a new device joins the network etc.
In the automation, i would like to include info such as IP, vendor, MAC address at a minimum. currently these are spread between multiple entities.

![Screenshot from 2024-06-11 17-09-11](https://github.com/jokob-sk/NetAlertX/assets/110621069/7fc88d2c-4bde-4057-afa8-4c2c92313729)

### Describe the solution you'd like

copy the same info from these other entities and include them as attributes for the device_tracker "device_tracker.DEVICE_is_present"

### Describe alternatives you've considered

it's honestly not necessary. One can build a more complex automation to hunt and parse this info. I think it's just a matter of optimisation to make the entities more user friendly.

### Anything else?

i should raise a different bug issue for this but can you remove the underscores for these entity names?

**Comment by jokob-sk** [comment]
![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/1a71542f-0350-4e98-ac37-6e4734cf3d44)
This should be available in the next release. Please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

👉If I don't get a confirmation that this is working I might pull out the feature to prevent bugs. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved/the new feature is working.

Thanks in advance,
j

**Comment by jokob-sk** [comment]
> i should raise a different bug issue for this but can you remove the underscores for these entity names?

Entity names are used in multiple places (e.g. in the topic) so I won't remove underscores unless really necessary. I don't want to introduce unnecessary complexity into the code if it can be avoided.

**Comment by jokob-sk** [comment]
Releasing -> closing
