### ISSUE TITLE
Strange behavior of cleanDeviceName

### ISSUE THREAD

**Issue by CRi83** [jokob-sk/NetAlertX#725]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

The domain I use for my LAN is something like *.home.example.com

NetAlertX properly resolves my devices name but then cleanDeviceName strips the ".home" part.
e.g.: "nas.home.example.com" becomes "nas.example.com"

I guess the goal was to clean the ".home" part only when it's at the end of the name (e.g.: "nas.home" become "nas").

I tried using NEWDEV_LESS_NAME_CLEANUP but then, it removes the whole domain part...
e.g.: "nas.home.example.com" becomes "nas"

### Expected Behavior

Only remove the ".home" part if it's at the end of a domain name.

### What branch are you running?

Production

### app.log

22:41:13 [NSLOOKUP] Domain Name: nas.home.example.com.
22:41:15 [Name cleanup] Using old cleanDeviceName(nas.home.example.com.)
22:41:15 cleanDeviceName = nas.example.com (IP match)

23:05:50 [NSLOOKUP] Domain Name: nas.home.example.com.
23:05:51 [Name cleanup] Using new cleanDeviceName(nas.home.example.com.)
23:05:51 [Name cleanup] cleanDeviceName = nas (IP match)

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hey @CRi83 ,

A new setting `NEWDEV_NAME_CLEANUP_REGEX` will be available in the next release. Please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved/the new feature is working.

⭐ This feature took 30h ⏳ to implement (loooooooots of refactoring) - consider becoming a sponsor or sharing the app on socials⭐

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/413abe88-427a-4210-9b73-e81f37a32e10)

Thinking about removing the `NEWDEV_LESS_NAME_CLEANUP` setting as a result. Ping @ulrichwisser @iptvcld

**Comment by CRi83** [comment]
Thank you very much!
I'll try the new version this week-end and confirm that it's working.

**Comment by CRi83** [comment]
Hi @jokob-sk,

I spun up a new container with the dev image and it's now working perfectly.
Thanks again for your hard work 👍

**Comment by jokob-sk** [comment]
Thanks for checking!

**Comment by jokob-sk** [comment]
Releasing -> closing
