### ISSUE TITLE
ARPSCAN, INTRNT, PHOLUS plugins can't be unloaded

### ISSUE THREAD

**Issue by iptvcld** [jokob-sk/NetAlertX#726]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Enabled Settings keep reappearing after disabling
For example, I have disabled Internet Check, Pholus and Arp-Scan and then un-selected the plugin from the list, Save. They go away.. Then when i make a different change and hit save again, i see a box saying warning, importing settings and they all come back. (Settings imported: 05/07/2024, 18:02:30)

### Expected Behavior

Once disabled and removed, dont come back

### Steps To Reproduce

Enabled Settings keep reappearing after disabling
For example, I have disabled Internet Check, Pholus and Arp-Scan and then un-selected the plugin from the list, Save. They go away.. Then when i make a different change and hit save again, i see a box saying warning, importing and they all come back. I have even deleted the docker image and re-configured it all (Dev) and same issue.

### What branch are you running?

Dev

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
This should be fixed in the next release. Please have a look at the newest `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

It would be great if you could test this (backup everything first or use a new container) on your end and letting me know if the issue was resolved.

Thanks in advance,
j

PS. Thank you for the donation ♥

**Comment by iptvcld** [comment]
Just pulled a new update and issue has been fixed. I tested multiple time disabling and unloading the plugins and they did not reappear. Thanks

**Comment by jokob-sk** [comment]
Releasing -> closing
