### ISSUE TITLE
Don´t publish MQTT Sensor if device name is "(name not found)"

### ISSUE THREAD

**Issue by AdmiralRaccoon** [jokob-sk/NetAlertX#732]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [X] Yes
- [ ] No

### Is your feature request related to a problem? Please describe

Many hostnames can not be resolved, and NetAlertX tags the name as (name not found). 

Usually, I will change the name manually, but the MQTT Plugin has already published the device to home Assistant, and the entites will have the name "sensor.name_not_found_last_ip_1, sensor.name_not_found_last_ip_2", and so on, resulting in renaming each entity in Home Assistant to the correct name.

### Describe the solution you'd like

If NetAlertX detects a device and can´t resolve the hostname and tags it as (Name not found), these devices should not been published by MQTT, as long as the device has not been renamed.

EDIT: After thinking about, it would be nice if this could be and optional feature for every subnet. If this would be a global feature, i wouldn´t be informed if there are any new devices in the guest vlan, as they often have blank names (especially android devices). And for guest devices, there is no need for manually naming.

### Describe alternatives you've considered

Renaming all entities manually in Home Assistant. :-D

### Anything else?

-

**Comment by jokob-sk** [comment]
Hey @AdmiralRaccoon ,

That makes sense.

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/d567a263-01ee-4bed-983e-e2de7ef2857c)


This should be available in the next release. Please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

👉If I don't get a confirmation that this is working I might pull out the feature to prevent bugs. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved/the new feature is working.

⭐ This feature took 30min ⏳ to implement - consider becoming a sponsor or sharing the app on socials⭐

Thanks in advance,
j

**Comment by AdmiralRaccoon** [comment]
thanks, I will test it as second thing in the morning. first thing is coffee

**Comment by AdmiralRaccoon** [comment]
I´ve tried testing it but I´m struggling getting the device page loaded:
The Loading Icon won´t disappear, I tried clearing cache, private window, another browser.

Usually, it disappears after some time, but today nothing happens since 1,5 hours.


![image](https://github.com/jokob-sk/NetAlertX/assets/41727850/f93730a6-d29d-487c-b44e-f18d8e082dfc)


However, when going through the "monitoring" tab, I can see my "Name not found" test devices, and this time they don´t appear within Home Assistant, so I guess it works.

**Comment by jokob-sk** [comment]
Great, thanks for checking! 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner. If the issue persists, please screenshot the Dev Console tab in your browser. I'm also pushing out a couple of fixes, but they should not influence this.

**Comment by jokob-sk** [comment]
Releasing -> closing
