### ISSUE TITLE
Omada plugin failing - possibly something to do with "firewall" object?

### ISSUE THREAD

**Issue by thefunkygibbon** [jokob-sk/NetAlertX#786]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Looking at the logs, I am seeing the plugin attempt to connect, getting the list of devices, but then bombing out with 

10:01:09 [OMDSDN] callomada:set-client-name 70-09-71-00-B3-0F 70-09-71-00-B3-0F
Traceback (most recent call last):
  File "/app/front/plugins/omada_sdn_imp/omada_sdn.py", line 450, in <module>
    main()
  File "/app/front/plugins/omada_sdn_imp/omada_sdn.py", line 204, in main
    device_data = get_device_data(clients_list, switches_and_aps, device_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/front/plugins/omada_sdn_imp/omada_sdn.py", line 436, in get_device_data
    device_data_bymac[default_router_mac][TYPE] = 'Firewall'           
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: '02-42-78-0A-6C-E4'


Not sure if its because it is expecting a firewall/router device on the omada system (which I don't have, nor desire)?
fwiw 70-09-71-00-B3-0F which is mentioned as the last mac address is a samsung tv.   and i'm not sure if the "keyerror" part is a MAC address too? but I don't have any devices which have that mac address on my network


### Expected Behavior

to work

### Steps To Reproduce

_No response_

### app.conf

_No response_

### docker-compose.yml

_No response_

### What branch are you running?

Production

### app.log

_No response_

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
@FlyingToto can you help out if you have time?

**Comment by thefunkygibbon** [comment]
Ok, so it may well be that it isn't going to work for me for some reason.

I have just gone through the docs and seen that it doesn't "support" EAP245 AP's (of which I have 3 of),   I'm unsure what about them it doesn't support though given that I figured most of all the details are picked up from the Omada controller platform/db itself?

Also I'm not using any of the Omada system for DHCP/DNS/Router/Firewall.  I'm only using it for Wifi and Switch management.   

But obviously the Omada system still contains all of the on/offline devices with their MACs/IPs/Names and so on.  So if its not something thats workable I guess I'll go back to using ARP/NMAP scanning

**Comment by thefunkygibbon** [comment]
ok not sure whats going on now.  nothing has changed other than sticking it on the host network instead of bridge,  configuring nmap and mapping pihole to work with it.   but its deffo picked up some stuff from the omada now.  I have a diagram showing whats connected to what AP etc (including EAP245's)

**Comment by FlyingToto** [comment]
- I can't help right now (my PC is still HS, waiting for the release of X870 so ETA probably October/November)
- correct the current client version of omada's python library doesn't seem to work with EAP245; however, the code should handle the exception gracefully, In the case of the EAP245, it just won't be able to identify other AP or switches connected downstream to the EAP245 itself (which should be very limited)
- you don't need to use a tp-link router/firewall/gateway. In fact in my case, I am only using switches and access points. 
- the error you get is indeed very odd and not omada specific, For some reasons, the code assumes your samsung TV is your default router.... would it be possible for you to:
1. enable log level = debug
2. clear the logs
3. let the whole cycle run twice (about 1h)
4. save the log and share it with me privately? 

When my PC is back online I will check it.

**Comment by FlyingToto** [comment]
I was just checking the code, real quick and I am trying to identify the default router with this logic:
"_try to find the default route by extracting the router associated with route 0.0.0.0"_ 

the "bridge" which was having the issue, what OS is it running? docker on linux? or linux or something else?

    f```
from scapy.all import conf, Route, sr1, IP, ICMP
    default_route = conf.route.route("0.0.0.0")
    return default_route[2] if default_route[2] else None
```

**Comment by thefunkygibbon** [comment]
I'm running docker on a Debian based os

**Comment by FlyingToto** [comment]
oh ok, so the problem was most likely that when using the bridge network it didn't have access to the whole hosts interfaces and would be limited to the bridge addresses. 
@jokob-sk , is netalertx supposed to run properly in bridge mode? I assume most ARP probes would fail wouldn't they?

**Comment by jokob-sk** [comment]
Also, thanks for the help @FlyingToto !

@thefunkygibbon double-checking - once you switched to host mode, everything works as expected?

**Comment by thefunkygibbon** [comment]
Hmm well I "think" so, but i'm seeing some other odd things which i need to look into to whats going on.  for example,  my fing says I have currently 59 devices online,  omada says 53 (but then I have 6 network devices, AP's and switches so that makes 59 and adds up ok) but netalert says I have 110 devices online!?

**Comment by jokob-sk** [comment]
Glad to hear it's mostly working. Please open a separate issue if it's setup-related as your app.log and settings may have changed since you've open this issue.

**Comment by FlyingToto** [comment]
> Hmm well I "think" so, but i'm seeing some other odd things which i need to look into to whats going on. for example, my fing says I have currently 59 devices online, omada says 53 (but then I have 6 network devices, AP's and switches so that makes 59 and adds up ok) but netalert says I have 110 devices online!?


yeah it is a bit tricky to interpret... 

- omada sdn split your "stuff" between devices (tp-link routers, switches, access points), clients (any hosts or non-tp-link network devices) 
- netalertx, tracks everything with a MAC address as device.  
- - So a router/hosts with multiple network cards with individual MAC will show as multiple thingies...  
- - Conversely, if a phone/PC uses anonymous MAC, it will show duplicate entries since the MAC addresses keep changing randomly...

**Comment by thefunkygibbon** [comment]
> > Hmm well I "think" so, but i'm seeing some other odd things which i need to look into to whats going on. for example, my fing says I have currently 59 devices online, omada says 53 (but then I have 6 network devices, AP's and switches so that makes 59 and adds up ok) but netalert says I have 110 devices online!?
> 
> yeah it is a bit tricky to interpret...
> 
> * omada sdn split your "stuff" between devices (tp-link routers, switches, access points), clients (any hosts or non-tp-link network devices)
> * netalertx, tracks everything with a MAC address as device.
> * * So a router/hosts with multiple network cards with individual MAC will show as multiple thingies...
> * * Conversely, if a phone/PC uses anonymous MAC, it will show duplicate entries since the MAC addresses keep changing randomly...

thanks,  i'll spend some time looking into it at some point i'm sure, but just to your points (in order)

- that's fine tbh, as long as all devices are in netalert it doesn't matter
- yup, I get that. 
- fwiw, i don't have anything i can think of that would be running multiple NIC's and so on.  The only thing i have that i can think of which might be doing something funky is my server which is running docker and my fingbox
- but things which anonymise the MAC are either connecting to the network for the first time or not actually connecting to the network at all (ie in fing , having the detections of different devices' mac address "being near to" not connected to the network, that functionality is next to useless now all phones use a different mac for each AP they are seen by).


just checked my netalert and weirdly it is saying only 2 devices are online now (?! totally wrong).  

out of interest , a couple of questions (for you both) 

1. does the plugin pull ALL devices old and new, into Netalert ?  or only the devices currently online?
2. when does the "new" flag stop being new for a device?  as it seems that every device on my list is "new" despite it being pulled in presumably 5 days ago when i first ran it.
3. and just thinking about it because i know fingbox seems to alert about a new device when it connects to a different AP on the network,  would the duplicates basically be different entries for the same device connecting to different AP's on my network?  (all omada and part of this infrastructure).
4. out of the list of "online devices" i see Green NEW's and Grey NEW's. I assume the grey ones imply that they are offline, but they are still considered online.   for example it says I have 113 devices,   104 "connected".  but as per my other comment, a lot of those most certainly are offline

I do see a bunch of duplicates in the netalert list such as this, I'm assuming it IS pulling in historic data from the Omada.   
![image](https://github.com/user-attachments/assets/a992bb2d-b89f-4630-99f6-dc569c77a716)


Also of note, I just checked the settings and found that the omada plugin was "disabled" - i didn't turn it off!?  very confusing.

**Comment by FlyingToto** [comment]
- These anonymous random MAC addresses are driving me nuts as well...  I would suggest you go to each phone and PC and disable the feature (since it is done per SSID, you can safely disable it for your home wifi, while keeping it on when you are out and about).
- in my case I have one work laptop where I can't disable the random MAC and I am using an ethernet cable to connect it home,, it still shows as dup less often it seems....
- AFAIK, when you change something in your netalertx config you really need to wait 2 cycles to check the outcome because of the way the plugin gets triggered and depend on each others. 
going back to your questions:

1. The omada plugin pulls all devices & clients from OMADA SDN; however, it doesn't know if they are online/offline. It only pulls the fact that SDN registered them with a given IP on a specific switch and port.  So it is conceptually possible that if omada sdn still shows your pixel7 with MAC 1:2:3:4:5:6 on AP245-kitchen but in reality you moved in your office and another probe like arpscan sees your same pixel7 with new MAC 1:2:3:4:5:7 on AP245-office  it would create a duplicate.  OMADA-SDN itself is not really clear on how long they keep clients in their cache or how they deal with dynamic MAC...  
2. AFAIK, the "new" flag stays there until you uncheck it yourself.  if it is a pain, you can change your default settings so they never mark something new as new.... 
3. whether it is fing, omada or other probes in netlartx, if you move a latop with a static MAC from one AP to another it should not create a duplicate since netalertx tracks by MAC address...  but if you have random MAC.... that doesn't work....  There is one exception I came across.... for some unclear reasons, sometime OAMADA SDN itself gets confused if you daisy chain switches I came across a  couple of case where devices behind switch 2 where showing up associated with switch2 MAC address connected to the switch1 port  used by switch2... usually this goes away if you do a ping... 
4. the online/offline status is not tracked by the omada sdn plugin, I think it is either by the arpscan or maybe another ping plugin (I will defer to @jokob-sk ).  The one case where I got offline devices showing as online was related to issue above where they got mapped to the MAC of the switch by mistake by omada sdn and the switch was online....

**Comment by FlyingToto** [comment]
one more thing, 
in your screenshot...  it looks like RANDOM Mac detection doesn't always work because your pixel7 phones sometimes match a real MAC vendor so definitely start by disabling the feature on your home SSIDs first. then you might want to clear all the devices and redo the scan.

**Comment by jokob-sk** [comment]
Thanks @FlyingToto for the in-depth support and replies!

> I think it is either by the arpscan or maybe another ping plugin (I will defer to @jokob-sk ). 

The online/offline status is tracked by most of the plugins (NMAPDEV/ARPSCAN/SNMP/DHCP).

That means you can combine multiple plugins to get the desired result.

@FlyingToto on a side-note, we could have a toggle setting "Import only online" which then could be used to track the online/offline status once the user decides to switch from an import to  tracking. Just an idea :)

**Comment by jokob-sk** [comment]
Thans a lot @FlyingToto - And no rush, just an idea for the backlog :) Fingers crossed the new MB is good 🤞
