### ISSUE TITLE
[Help needed] Freebox device scanner

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/NetAlertX#799]
It would be amazing if someone from the community could add a Freebox plugin. 

The API (https://dev.freebox.fr/sdk/os/) seems to be documented, but unsure if devices and their status is available. 

You can check the UNIFI plugin to get inspired/as a starting point: https://github.com/jokob-sk/NetAlertX/tree/main/front/plugins/unifi_import

There is also a 15-minute video on how to create a plugin: https://github.com/jokob-sk/NetAlertX/blob/main/docs/PLUGINS_DEV.md

Thanks in adbvance for your help!

Users who would benefit from this: @azertylr

**Comment by azertylr** [comment]
Hello,
The connected devices seem to be available here : https://dev.freebox.fr/sdk/os/lan/#lan-browser

**Comment by leiweibau** [comment]
A Freebox appears to have several interfaces. You would first have to determine the list of interfaces with “/api/v4/lan/browser/interfaces/” and then query the list of hosts per interface via “/api/v4/lan/browser/{interface}/”. At least that's what the API documentation leads me to believe.

I cannot say whether the “uid” is sufficient for authentication or whether it is necessary for all things. In case of doubt, you would first have to determine this via “/api_version”. If authentication is necessary, which I can well imagine in the case of the Lan browser, then the first step is to log in via “/api/v4/login/authorize/”.

At the end, I would also recommend logging out, otherwise you may reach the session limit of the Freebox.

Why can I say so much about this topic? I've been struggling with the Pi-hole 6 API for days 😉

**Comment by jokob-sk** [comment]
Thanks a lot for the details @leiweibau - figuring put APIs can be _FUN_ - let's see if someone from the community can help 🙏

**Comment by KayJay7** [comment]
I have published a pull request adding a plugin for the Freebox API ([!901](https://github.com/jokob-sk/NetAlertX/pull/901)), though the gateway'a API offer multiple names for the same device, that the gateway obtains through different protocols.\
Some devices use different names in those protocols and you need to see all of them to understand which device it is. It would be useful if a plugin had a proper way to store multiple names for a device, so that the user can navigate them and choose an appropriate display name.

**Comment by jokob-sk** [comment]
Releasing -> Closing
