### ISSUE TITLE
Devices not visible if connected to a wifi extender

### ISSUE THREAD

**Issue by Metathesus** [jokob-sk/NetAlertX#852]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Devices not visible if connected to a wifi extender!
Logs are spammed, it  show the mac adress of the repeater and multiple IP change.

### Expected Behavior

All devices are visible

### Steps To Reproduce

I use a wifi extender (wifi repeater) TP-Link RE305
All device connecter to the repeater are not visible

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @Metathesus ,

That behavior is expected. A Wi-Fi extender typically works by creating a separate network or subnet, which can cause certain network scanning tools, like arp-scan, to be unable to detect devices behind the extender.

This happens because arp-scan uses ARP (Address Resolution Protocol) to map IP addresses to MAC addresses on the local network. Since ARP is a Layer 2 (data link layer) protocol, it usually only works within a single broadcast domain, which is typically limited to a single router or network segment.

When you introduce a Wi-Fi extender, it may isolate devices on different segments of the network, meaning ARP packets cannot easily traverse from one segment (your main network) to another (the network behind the extender).

To scan devices behind the extender, you can try:

- Scanning the specific subnet that the extender uses, if it is separate from the main network.
- Using [supplementing plugins](https://github.com/jokob-sk/NetAlertX/blob/main/front/plugins/README.md) that use alternate methods. Protocols used by the `SNMPDSC` or `DHCPLSS` plugins have good support and usually can be used as a workaround.

Check the [plugins list](https://github.com/jokob-sk/NetAlertX/blob/main/front/plugins/README.md) to find a plugin supported by your router and  your network setup. 

Hope this helps,
j

**Comment by Metathesus** [comment]
Hi, Thanks for your explanations and all your works!

**Comment by tradexsrl** [comment]
Hi , i have a similar problem with 2 ip camera connected to a wifi extender that have same ssid of the main AP , netalertx doesn't find the two camera but if inside the container i issue a console ping command to both static ip i get a reply 👍 
i'm attaching stdoutlog and app.conf

[log-conf.zip](https://github.com/user-attachments/files/25024155/log-conf.zip)

<img width="601" height="592" alt="Image" src="https://github.com/user-attachments/assets/28a83514-03e8-4258-8602-50d86186d5fe" />

**Comment by jokob-sk** [comment]
Hi @tradexsrl ,

Please read this: https://docs.netalertx.com/REMOTE_NETWORKS/?h=remote
