### ISSUE TITLE
Error with Networking Module

### ISSUE THREAD

**Issue by mpalls** [jokob-sk/NetAlertX#883]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [X] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

I'm getting this error when I go to Networking: "[ERROR] \u26a0 Infinite recursion detected. You probably have assigned the Internet node to another children node or to itself. Please open a new issue on GitHub and describe how you did it."

### Expected Behavior

Should see the Networking hierarchy. I don't get anything but the aforementioned error. 

### Steps To Reproduce

I inadvertently assigned the internet node to something.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @mpalls ,

Can you please let me know how you configured the network nodes to end up in this state? What plugins did you enable?
Any more details would be appreciated. 

Thanks,
j

**Comment by Strux-DK** [comment]
I'm not OP, but i am in the exact same situation. I assigned the Internet node to my router, thinking that was the right thing to do, but obviously not. Now i can't delete the connection.
How did i configure the network nodes to end in this state? Not sure, becuase i was setting up all my devices for the first time, so i just "speed-ran" it all, but i guess at some point i thought "Oh! Have to remember to assign the other end of the internet connection" and then went into the "internet" node and assigned it to be connected to my router. It wasn't until after going through all my devices that i found out something was wrong in the "network" tab.
However, different from @mpalls situation is, i can see the network overview, there's just a popup with the warning after a couple of seconds, i click "ok" and then i can still see the network overview.
![billede](https://github.com/user-attachments/assets/863c3453-158b-42f0-9d53-684dddac0a9d)
Dragged away from the overview to keep my devices private.
Plugins:
![billede](https://github.com/user-attachments/assets/1c5b40dc-b64f-478a-a018-c7f7d98054d7)

I hope it's okay i ask something else here:
Is it possible to have a NAS as a network device on the same basis as a hypervisor? I run some small containers and VMs on my NAS, but i can't assign them properly as child notes, since the NAS isn't considered a network node. I would love for a change like that.

Anyways thanks for the amazing work! I love it already

**Comment by jokob-sk** [comment]
Hi @Strux-DK ,

You can add the `Parent node MAC` column to the `UI_device_columns` setting so you can identify the node that might cause the issue.

Then either fix it on the device details or in Maintenance - Multiedit. 

Please let me know if you remember how you did it. 

You can configure what is considered a Network device in the `NETWORK_DEVICE_TYPES` setting.

j

**Comment by Strux-DK** [comment]
Thanks for the help!
I got it all working now thanks!

I got some additional questions, i hope you don't mind:
1. Is Netalertx capable of somehow discover/track docker containers that share the same IP but has different ports?
2. My TP-link switch status is changing about every 5 mins. Do you have any idea why?
![billede](https://github.com/user-attachments/assets/4adbce00-c354-4a91-9f0a-2a7e96e23b03)

**Comment by jokob-sk** [comment]
Hi,

Glad to hear it's working.

If you figure out how this happened in the first place, please let me know. 

1. I think this depends on which interfaces you add to scan. It will still show one entry even if multiple ports are exposed. The NMAP plugin allows you to discover ports of devices.
2. Unsure, but the interval seems inconsistent, so I think it is network or device dependent. If it was the application I would expect to to be consistent. You can increase the `NTFPRCS_alert_down_time` when to mark the device down.

Hope this helps.
j

**Comment by jokob-sk** [comment]
No reply for a week -> closing
