### ISSUE TITLE
Undeliverable Email; Missing Date Field

### ISSUE THREAD

**Issue by NWBx01** [jokob-sk/NetAlertX#885]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [X] N/A - This is an issue with the backend

### Current Behavior

Unable to send notification emails while using docker-mailserver. Email hits bounces and returns to the sender inbox with the following message:

```
INVALID HEADER

  Missing required header field: "Date"
```

Sure, enough. There does not appear to be a date field in the email:
https://github.com/jokob-sk/NetAlertX/blob/4e90a82ea4cc3748c65d704472e1557136828e70/front/plugins/_publisher_email/email_smtp.py#L116-L122

### Expected Behavior

Notification email would be sent to receiving inbox.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thanks for the report. 

This should be fixed in the next release. It would be great if you could test this. Can you please set up an instance of the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now?

⚠please don't reuse your existing config or DB, I'm currently modifying those ⚠

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by jokob-sk** [comment]
Another workaround is to use a different SMTP server, GMAIL/GMX work even without the Date field: https://github.com/jokob-sk/NetAlertX/blob/4e90a82ea4cc3748c65d704472e1557136828e70/docs/SMTP.md

**Comment by NWBx01** [comment]
> Can you please set up an instance of the `netalertx-dev` docker image (backup everything at first)

This worked! Thanks!
