### ISSUE TITLE
Alert Down after x attempts

### ISSUE THREAD

**Issue by AlexRJ-FR** [jokob-sk/NetAlertX#886]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some important devices (under "Alert Down") need to reboot periodically. It takes +/- 3 minutes.
The alert is not necessary.

### Describe the solution you'd like

Next to the Alert Down opt case :
Only after xx attempts. (if zero, then alerts immediately)

The system would alert only if after xx attempts the devices is still down

### Describe alternatives you've considered

Nothing

### Anything else?

Nothing

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [X] No

**Comment by jokob-sk** [comment]
Hi @AlexRJ-FR ,

There is already a setting called `NTFPRCS_alert_down_time`. Did you consider using this setting?

> After how many minutes a device is reported as down and a notification is sent.

**Comment by leiweibau** [comment]
Hello @jokob-sk. As I have also just been looking into this topic a little, I hope that you might be able to answer 2 questions about this function.

Is this a global function or a feature per device?

I could find 2 queries in your code that work with this variable. Are you doing more extensive filtering, or is it really just these two queries?

https://github.com/search?q=repo%3Ajokob-sk%2FNetAlertX%20NTFPRCS_alert_down_time&type=code

I would be happy if you could find the time to answer me.

**Comment by jokob-sk** [comment]
Hi @leiweibau 👋

Hope you are well! 🙂

I implemented is a global setting and I didn't get any requests for per-device specific functionality. I _think_ I considered per-device settings, but I imagined most of the use cases you want his to behave the same. There is a possibility to extend this to device specific settings in the future, but I think the maintenance of code is not worth it at this point. 

I think the changes were not too extensive, it's been a while since I implemented this. Looking at the commits history - this might be the commit in question: https://github.com/jokob-sk/NetAlertX/commit/8e0eb6a480c484634215ed7d342f770d0748bf26

The feature was introduced in the version v24.01.18 so you can probably compare it to the previous one. 

Hope this helps, ask away if you find something in the code you'd like to check,
j

**Comment by jokob-sk** [comment]
No reply for a week -> closing
