### ISSUE TITLE
Container health: unhealthy with no last output

### ISSUE THREAD

**Issue by somar05** [jokob-sk/NetAlertX#922]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

Since the last update v24.12.23 I have receiving unhealthy warnings with no "last output". I have checked the log but I can't find tracks to locate the problem

### Expected Behavior

Last output shoould show some info regarding the issue

### Steps To Reproduce

Just update to v24.12.23

### app.conf

```python
Too big for paste here. Please, ask for it if required
```

### What branch are you running?

Production

### app.log

Too big for paste here. Please, ask for it if required

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @somar05 ,

The health check pings this URL, so try accessing it to see if there are any issues:

`${LISTEN_ADDR}:${PORT}/php/server/query_json.php?file=app_state.json`


```json
{
    "currentState": "Process: Idle",
    "lastUpdated": "2024-12-28 07:07:51+11:00",
    "settingsSaved": 1735269547.0351722,
    "settingsImported": 1735269547.0351722,
    "showSpinner": false,
    "isNewVersion": false,
    "isNewVersionChecked": 1735327203,
    "graphQLServerStarted": 1
}
```

**Comment by somar05** [comment]
Hi @jokob-sk . Thx for your reply.
The response looks fine. In this case if i put the url 

`http://192.168.1.99:20211/php/server/query_json.php?file=app_state.json` 

I get this one:

```
{
    "currentState": "Process: Idle",
    "lastUpdated": "2024-12-28 06:47:00+01:00",
    "settingsSaved": 1735364358.672956,
    "settingsImported": 1735364358.672956,
    "showSpinner": false,
    "isNewVersion": false,
    "isNewVersionChecked": 1735362834,
    "graphQLServerStarted": 1
}
```

**Comment by somar05** [comment]
I have found some lines regarding this issue in the 'nginx/error.log'. I have multiple lines like this that probably are related with this issue:

`2024/12/28 07:19:55 [error] 187#187: *121 open() "/app/front/api/app_state.json" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /api/app_state.json HTTP/1.1", host: "0.0.0.0:20211"`

**Comment by jokob-sk** [comment]
Hi @somar05 ,

The `/app/front/api/app_state.json` location is the old one, which was replaced by the above mentioned url `/php/server/query_json.php?file=app_state.json`. I think the health check is stored agains teh container config tor something, because it seems to remember the old location. 

By running `docker exec -it a1ae20e77b51 touch /app/front/api/app_state.json` you tricked it - because this location is invalid since the last release. 

Not sure why the health check is pinging the old location though. If the container is running without issues, then no harm done, I'd preemptively create a second instance with a new container name just to be sure, or stop the container, remove everything, including the volumes, delete the image, and spin it up again. 

As always, make sure your backups are always available: https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md

Hope this helps,
j

**Comment by somar05** [comment]
Hi @jokob-sk 
I have create a second instance after follow your recomendations and the health check is fine now. No idea why after upgrade to v24.12.23 the health check was searching the old location. Anyway, I have now the new container as the main one after restore the backup.
Thanks for your help, and pls, close the issue if you agree

Thanks!!

**Comment by jokob-sk** [comment]
Glad to hear that - and thanks a lot for the coffees 🙂
